### ISSUE TITLE
Lose connection 

### ISSUE THREAD

**Issue by Technik-Tueftler** [Technik-Tueftler/Speedtest#10]
# What
Program stops, with following error message

# Error
Next measurement attempt: 22-04-15 07:30:02
Check network load: ok
Start new Speedtest measurement
Exception in thread Thread-3306 (measure_connection_speed):
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/speedtest.py", line 1493, in get_best_server
    fastest = sorted(results.keys())[0]
IndexError: list index out of range
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "/user/app/./Speedtest/source/main.py", line 118, in measure_connection_speed
    connection.get_best_server()
  File "/usr/local/lib/python3.10/site-packages/speedtest.py", line 1495, in get_best_server
    raise SpeedtestBestServerFailure('Unable to connect to servers to '
speedtest.SpeedtestBestServerFailure: Unable to connect to servers to test latency.

**Comment by Technik-Tueftler** [comment]
done
