### ISSUE TITLE
No module named 'psycopg2' - Unable to use Postgres-Database

### ISSUE THREAD

**Issue by mbedded** [Technik-Tueftler/Speedtest#9]
Hello Tetü,

I cloned the repository and built the Dockerfile by myself using "python:3.10.4-buster" because the Container won't be used on an ARM-Based device. 

The connection-string for the database was copy&pasted from the README.
I used the following docker-compose to start the application:

```
version: "3.9"

services:
  speedtest:
    image: speedtest:01
    restart: always
    environment:
      - DB_CONNECTOR=postgresql+psycopg2://speedtest:speedtest@myDatabaseServer/speedtest
      - TEST_REPEAT_TIME=3600
      - TEST_REPETITION_TIME=7200
      - IP_FRITZBOX=fritz.box
```

Unfortunately I see an issue in the logs when the Container is started:

```
Start program
Traceback (most recent call last):
  File "/user/app/./Speedtest/source/main.py", line 255, in <module>
    verified_env_data = check_and_verify_env_variables()
  File "/user/app/./Speedtest/source/main.py", line 248, in check_and_verify_env_variables
    db.check_and_verify_database_connection()
  File "/user/app/Speedtest/source/db.py", line 69, in check_and_verify_database_connection
    engine = create_engine(connector)
  File "<string>", line 2, in create_engine
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/util/deprecations.py", line 309, in warned
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/create.py", line 560, in create_engine
    dbapi = dialect_cls.dbapi(**dbapi_args)
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/dialects/postgresql/psycopg2.py", line 782, in dbapi
    import psycopg2
ModuleNotFoundError: No module named 'psycopg2'
```

It seems that a package is missing which should be added to the requirements-file.

Best regards
Matthias

**Comment by mbedded** [comment]
Update: I just added the following line to requirements.txt
```
psycopg2==2.9.3
```

I rebuilt the project using `docker build` started the container again and the measurement was added to the database

**Comment by Technik-Tueftler** [comment]
thanks for the hint, done
